# .goreleaser.yml
# Build customization
builds:
  - binary: telegraf-freeswitch
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -a
    ldflags:
     - -s -w
    env:
      - CGO_ENABLED=0
archive:
  format: tar.gz
  files:
    - contrib/telegraf-freeswitch.service
